module HTTPCodes
  HTTP_SUCCESS = '200'.freeze
  HTTP_CREATED = '201'.freeze
  HTTP_MULTIPLE_CHOICES = '300'.freeze
  HTTP_UNAUTHORIZED = '401'.freeze
  HTTP_NOT_FOUND = '404'.freeze
  HTTP_SUCCESS_CODES = [HTTP_SUCCESS, HTTP_CREATED, HTTP_MULTIPLE_CHOICES].freeze
end
